"""
Django settings for classroom_ge project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from .my_constants import (
    DATABASE_PARAMS,
    allowed_hosts,
    django_debug,
    django_dev,
    django_secret_key,
    captcha_public_key,
    captcha_private_key,
    email_host_,
    email_host_password_,
    email_port_
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = django_secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = django_debug

ALLOWED_HOSTS = allowed_hosts

# SSH
if not django_dev:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    DEVELOPMENT_MODE = False
else:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    DEVELOPMENT_MODE = True
# Application definition



# Application definition

INSTALLED_APPS = [
    'modeltranslation',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'base.apps.BaseConfig',
    'app_student.apps.AppStudentConfig',
    'app_teacher.apps.AppTeacherConfig',
    'app_administrator.apps.AppAdministratorConfig',

    'django_extensions',
    'captcha',
]

AUTH_USER_MODEL = 'base.User'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "classroom_ge.middlewares.force_default_language.force_default_language_middleware",
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'classroom_ge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'classroom_ge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'classroom_ge',
        'USER': DATABASE_PARAMS['USER'],
        'PASSWORD': DATABASE_PARAMS['PASSWORD'],
        'HOST': DATABASE_PARAMS['HOST'],
        'PORT': DATABASE_PARAMS['PORT'],
    },
    'TEST': {
        'NAME': 'test_classroom_database',
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'ka'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = (
    ('ka', _('Georgian')),
    # ('en', _('English')),
)

LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "assets/"
STATIC_ROOT = os.path.join(BASE_DIR, 'assets/')

STATICFILES_DIRS = [
    ('moderator', os.path.join(BASE_DIR, 'static_files', 'app_administrator')),
    ('student', os.path.join(BASE_DIR, 'static_files', 'app_student')),
    ('teacher', os.path.join(BASE_DIR, 'static_files', 'app_teacher')),
    ('base', os.path.join(BASE_DIR, 'static_files', 'base')),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Gootle reCaptcha
RECAPTCHA_PUBLIC_KEY = captcha_public_key
RECAPTCHA_PRIVATE_KEY = captcha_private_key

# For sending emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = email_port_
EMAIL_HOST_USER = email_host_
EMAIL_HOST_PASSWORD = email_host_password_
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

PASSWORD_RESET_TIMEOUT = 14400 # Tokens live for 4 hours

FIXTURE_DIRS =  os.path.join(BASE_DIR, 'fixtures/') 